# Generated by Django 4.2 on 2025-04-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0002_remove_partitura_ensamble_and_more'),
        ('ensambles', '0002_alter_ensamble_options_ensamble_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensamble',
            name='partituras',
            field=models.ManyToManyField(blank=True, related_name='ensambles', to='partituras.partitura'),
        ),
    ]
